baseURL = "https://mzylgl.github.io"
languageCode = "zh-CN"
title = "Mzyl的博客"
theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

disqusShortname = ""  ## 是否开启disqus评论，不要和utteranc同时开启


[author]
  name = "Mzyl"


[params]
  author = "Mzyl"
  subtitle = "记录自己的所想所思"
  keywords = ""
  description = ""
  busuanzi = false #启用不算子网页统计
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  # customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  # customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录


## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = false
  # repo = "your github repo" ##换成自己得
  # issueTerm = "pathname"
  # theme = "github-light"


## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"


## 配置网站菜单
[menu]

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:title/"
